import Head from 'next/head';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styled from 'styled-components';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Prc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Index Page</div>
      <NavTab>
        <Link href="/count">Count Page</Link>
        <Link href={`/segment/${encodeURIComponent('hello')}`}>
          Segment Page
        </Link>
        <Link
          href={{
            pathname: '/optionalSegments/[[...slug]]',
            query: { slug: ['hello', 'hi', 'bye'] },
          }}
        >
          OptionalSlug Page
        </Link>
        <Link href={`/multiSegment/post/1/hello`}>SegmentInSegment</Link>
        <Link href={`/todoList`}>TodoListPage</Link>
      </NavTab>
    </>
  );
}

const NavTab = styled.div`
  display: flex;
  flex-direction: column;
`;
